version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: fastapi_db
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app:/app
      - ./db/migration:/db/migration

  flyway:
    image: flyway/flyway:latest
    environment:
      FLYWAY_URL: jdbc:postgresql://db:5432/fastapi_db
      FLYWAY_USER: fastapi_user
      FLYWAY_PASSWORD: 123456
    volumes:
      - ./db/migration:/flyway/sql
    depends_on:
      - db

volumes:
  pg_data:
