version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: fastapi_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Exposing port 5432 from the container to 5433 on the host

  flyway:
    image: flyway/flyway:latest
    environment:
      FLYWAY_URL: jdbc:postgresql://db:5432/fastapi_db
      FLYWAY_USER: fastapi_user
      FLYWAY_PASSWORD: 123456
    volumes:
      - ./db/migration:/flyway/sql  # Pointing to your migration SQL files
    depends_on:
      - db  # Ensures the `db` service starts before Flyway runs

volumes:
  pg_data:
